### ISSUE TITLE
try to run your package in a project

### ISSUE THREAD

**Issue by scheiblr** [MatejMazur/react-schema-form#1]
Hi,

we try to run your package in a project. Unfortunately it does not work as described.
(get some problems with the @ in the include and it does not work differently)

Is there any chance to contact you, as we maybe wanna distribute.

Kind regards

**Comment by MatejMazur** [comment]
Hi @scheiblr sorry for any misunderstanding. The repo is not working yet. It's under development but I don't have account with a private repos so it's public even before finishing.

**Comment by scheiblr** [comment]
I just wanted to use it prematurely. I cannot really get it work. I cannot build the script and nothing..

**Comment by MatejMazur** [comment]
Because there is only the raw idea how it should work. The code is not completed.

**Comment by scheiblr** [comment]
ah, ok. Just for the information (don't wanna stress you): when do you think can we expect a first version?
Do you need specific help?

**Comment by MatejMazur** [comment]
I would like to accomplish this before the end of august.

The current problem what I solve is the internal structure of the schema, uiSchema and values. Because I would like to use a subscription pattern (with `React.createContext`) so you can rerender only the SchemaField directly related to the changed value. But that means that I need to invent an internal API for the manipulation with nested objects because if I leave the schema, uiSchema and values nested then I can't just to use shallow equality because every change deeply inside of them cause inequality of all the entities above the currently changed entity.
